import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Admin",
      email: "admin@admin.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Jhon",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Hunting bag",
      slug: "hunting-bag",
      category: "Bags",
      image: "/images/bag.jpg",
      price: 70,
      brand: "Askar",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A bag only for true askars!",
    },
    {
      name: "Hunting boots",
      slug: "hunting-boots",
      category: "Boots",
      image: "/images/boots.jpg",
      price: 80,
      brand: "Askar",
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: "A pair of boots for true askars!",
    },
    {
      name: "Complete bush dress",
      slug: "bush-dress",
      category: "Bush",
      image: "/images/bush.jpg",
      price: 90,
      brand: "Askar",
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: "Be a bush like a true askar!",
    },
    {
      name: "Hunting gloves",
      slug: "hunting-gloves",
      category: "Gloves",
      image: "/images/gloves.jpg",
      price: 90,
      brand: "Askar",
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Askar gloves for askar people",
    },
    {
      name: "Hunting jacket",
      slug: "hunting-jacket",
      category: "Jackets",
      image: "/images/jacket.jpg",
      price: 95,
      brand: "Askar",
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: "Very good looking jacket!",
    },
    {
      name: "Hunting knife",
      slug: "hunting-knife",
      category: "Knifes",
      image: "/images/knife.jpg",
      price: 75,
      brand: "Askar",
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: "Best knife in the world",
    },
  ],
};

export default data;
